#!/bin/bash
# Output changed files classified into code / config / docs / ignored sections.
# Code files are grouped into ~500 line chunks. Config files are grouped by
# Helm chart (with unchanged values.yaml/Chart.yaml added as context).
#
# Usage: diff-files.sh [base]
#   base: branch/commit to compare against (e.g., main, origin/main)
#         if omitted, shows staged + unstaged changes (git diff HEAD)

set -euo pipefail

BASE="${1:-}"
CHUNK_BUDGET=500

# Get changed files with diff stats (additions + deletions) and change status
if [[ -n "$BASE" ]]; then
    numstat=$(git diff "$BASE"...HEAD --numstat 2>/dev/null || true)
    namestatus=$(git diff "$BASE"...HEAD --name-status 2>/dev/null || true)
else
    # Staged + unstaged changes
    numstat=$(git diff HEAD --numstat 2>/dev/null || true)
    namestatus=$(git diff HEAD --name-status 2>/dev/null || true)
fi

# Build a "path<TAB>status" table. Renames list old and new path; key on the new
# one. Plain text rather than an associative array — bash 3.2 lacks declare -A.
status_table=""
while IFS=$'\t' read -r code p1 p2; do
    [[ -z "$code" ]] && continue
    case "${code:0:1}" in
        A) word="added" ;;
        D) word="deleted" ;;
        R) word="renamed" ;;
        C) word="copied" ;;
        *) word="modified" ;;
    esac
    # For R/C the new path is the second field
    if [[ -n "${p2:-}" ]]; then
        status_table+="$p2	$word"$'\n'
    else
        status_table+="$p1	$word"$'\n'
    fi
done <<< "$namestatus"

status_of() {
    local want="$1" p s
    while IFS=$'\t' read -r p s; do
        [[ "$p" == "$want" ]] && { echo "$s"; return; }
    done <<< "$status_table"
    echo "modified"
}

if [[ -z "$numstat" ]]; then
    echo "No changed files"
    exit 0
fi

# Classify a file into code|config|docs|ignored, echoing "class reason".
classify() {
    local filepath="$1"
    local base ext
    base="$(basename "$filepath")"
    ext="${filepath##*.}"
    [[ "$filepath" == "$ext" ]] && ext="none"

    # Vendored / build output — never review
    case "$filepath" in
        .git/*|*/.git/*) echo "ignored vendored"; return ;;
        node_modules/*|*/node_modules/*) echo "ignored vendored"; return ;;
        vendor/*|*/vendor/*) echo "ignored vendored"; return ;;
        dist/*|*/dist/*|build/*|*/build/*) echo "ignored vendored"; return ;;
    esac

    # Generated by filename pattern
    case "$base" in
        *.gen.*|*_gen.*|*.pb.go|*.pb.ts|*_generated.*|*.generated.*)
            echo "ignored generated"; return ;;
    esac

    # Lockfiles
    case "$base" in
        *.lock|go.sum|package-lock.json|yarn.lock|Cargo.lock|poetry.lock|pnpm-lock.yaml)
            echo "ignored lockfile"; return ;;
    esac

    # Generated by header comment — only read files that still exist
    if [[ -f "$filepath" ]]; then
        if head -5 "$filepath" 2>/dev/null | grep -qE '^[[:space:]]*(//|#|--|/\*)[[:space:]]*(Code generated|Generated by|DO NOT EDIT|@generated)'; then
            echo "ignored generated"; return
        fi
    fi

    # Docs
    case "$ext" in
        md|txt|rst|adoc) echo "docs documentation"; return ;;
    esac

    # CI workflows are config regardless of extension
    case "$filepath" in
        .github/workflows/*|*/.github/workflows/*) echo "config workflow"; return ;;
    esac

    # Config by filename
    case "$base" in
        Dockerfile|Dockerfile.*|.env|.env.*) echo "config container"; return ;;
    esac

    # Config by extension
    case "$ext" in
        yaml|yml|json|toml|ini|tf|tfvars|tpl) echo "config config"; return ;;
    esac

    echo "code source"
}

# Find the chart root for a config file: the longest path prefix that contains
# a Chart.yaml. Longest wins so subcharts beat their parent. Echoes "" if none.
chart_root_for() {
    local filepath="$1"
    local dir best=""
    dir="$(dirname "$filepath")"
    while [[ "$dir" != "." && "$dir" != "/" ]]; do
        if [[ -f "$dir/Chart.yaml" ]]; then
            best="$dir"
            break
        fi
        dir="$(dirname "$dir")"
    done
    echo "$best"
}

# Trailing annotation for a file line: "+N -M" plus a status tag when the change
# is not a plain modification. Adds and deletes are all-one-sided, so the split
# adds nothing there — the status tag already says it.
annotate() {
    local status="$1" added="$2" deleted="$3" out=""
    case "$status" in
        added|deleted) ;;
        *) out="	+$added -$deleted" ;;
    esac
    [[ "$status" != "modified" ]] && out+="	($status)"
    echo "$out"
}

declare -a code_data=() config_data=() docs_data=() ignored_data=()
total_lines=0
file_count=0

while IFS=$'\t' read -r added deleted filepath; do
    [[ -z "$filepath" ]] && continue

    # Handle binary files (shown as "-" in numstat)
    if [[ "$added" == "-" ]]; then
        added=0
        deleted=0
    fi

    # Renames appear as "old => new" in numstat — keep the new path.
    if [[ "$filepath" == *" => "* ]]; then
        filepath="${filepath##* => }"
        filepath="${filepath%\}}"
    fi

    lines=$((added + deleted))
    total_lines=$((total_lines + lines))
    file_count=$((file_count + 1))

    status="$(status_of "$filepath")"

    read -r class reason <<< "$(classify "$filepath")"

    case "$class" in
        code)
            ext="${filepath##*.}"
            [[ "$filepath" == "$ext" ]] && ext="none"
            code_data+=("$lines|$ext|$(dirname "$filepath")|$filepath|$status|$added|$deleted")
            ;;
        config)
            root="$(chart_root_for "$filepath")"
            [[ -z "$root" ]] && root="loose"
            config_data+=("$root|$lines|$filepath|$status|$added|$deleted")
            ;;
        docs)    docs_data+=("$lines|$filepath|$status|$added|$deleted") ;;
        ignored) ignored_data+=("$filepath|$reason") ;;
    esac
done <<< "$numstat"

if [[ $file_count -eq 0 ]]; then
    echo "No changed files"
    exit 0
fi

echo "Files: $file_count ($total_lines lines total)"
echo ""

# ---------------------------------------------------------------- Code section
if [[ ${#code_data[@]} -gt 0 ]]; then
    IFS=$'\n' sorted=($(sort -t'|' -k2,2 -k3,3 <<< "${code_data[*]}")); unset IFS

    declare -a chunks=()
    current_chunk=""
    current_lines=0
    code_lines=0

    for entry in "${sorted[@]}"; do
        IFS='|' read -r lines ext dir filepath status added deleted <<< "$entry"
        code_lines=$((code_lines + lines))

        if [[ $current_lines -gt 0 && $((current_lines + lines)) -gt $CHUNK_BUDGET ]]; then
            chunks+=("$current_chunk")
            current_chunk=""
            current_lines=0
        fi

        [[ -n "$current_chunk" ]] && current_chunk+=$'\n'
        current_chunk+="  $filepath	$lines$(annotate "$status" "$added" "$deleted")"
        current_lines=$((current_lines + lines))
    done

    [[ -n "$current_chunk" ]] && chunks+=("$current_chunk")

    chunk_word="chunks"
    [[ ${#chunks[@]} -eq 1 ]] && chunk_word="chunk"
    echo "## Code (${#code_data[@]} files, $code_lines lines, ${#chunks[@]} $chunk_word)"
    echo ""

    chunk_num=1
    for chunk in "${chunks[@]}"; do
        chunk_lines=0
        while IFS= read -r line; do
            [[ -z "$line" ]] && continue
            # Field 2 is the line count (field 3, if present, is the status tag)
            l=$(echo "$line" | awk -F'\t' '{print $2}')
            chunk_lines=$((chunk_lines + l))
        done <<< "$chunk"

        echo "Chunk $chunk_num ($chunk_lines lines):"
        echo "$chunk"
        echo ""
        chunk_num=$((chunk_num + 1))
    done
fi

# -------------------------------------------------------------- Config section
if [[ ${#config_data[@]} -gt 0 ]]; then
    IFS=$'\n' sorted_cfg=($(sort -t'|' -k1,1 <<< "${config_data[*]}")); unset IFS

    config_lines=0
    for entry in "${sorted_cfg[@]}"; do
        IFS='|' read -r root lines filepath status added deleted <<< "$entry"
        config_lines=$((config_lines + lines))
    done

    # Count distinct groups
    group_count=$(printf '%s\n' "${sorted_cfg[@]}" | cut -d'|' -f1 | sort -u | wc -l | tr -d ' ')

    group_word="groups"
    [[ "$group_count" -eq 1 ]] && group_word="group"
    echo "## Config (${#config_data[@]} files, $config_lines lines, $group_count $group_word)"
    echo ""

    current_root=""
    for entry in "${sorted_cfg[@]}"; do
        IFS='|' read -r root lines filepath status added deleted <<< "$entry"

        if [[ "$root" != "$current_root" ]]; then
            # Close previous group with its context files
            if [[ -n "$current_root" && "$current_root" != "loose" ]]; then
                for ctx in "$current_root/values.yaml" "$current_root/Chart.yaml"; do
                    if [[ -f "$ctx" ]] && ! printf '%s\n' "${sorted_cfg[@]}" | grep -q "|$ctx\$"; then
                        echo "  context: $ctx"
                    fi
                done
            fi
            [[ -n "$current_root" ]] && echo ""

            if [[ "$root" == "loose" ]]; then
                echo "Group loose:"
            else
                echo "Group $root (chart):"
            fi
            current_root="$root"
        fi

        echo "  $filepath	$lines$(annotate "$status" "$added" "$deleted")"
    done

    # Context for the final group
    if [[ -n "$current_root" && "$current_root" != "loose" ]]; then
        for ctx in "$current_root/values.yaml" "$current_root/Chart.yaml"; do
            if [[ -f "$ctx" ]] && ! printf '%s\n' "${sorted_cfg[@]}" | grep -q "|$ctx\$"; then
                echo "  context: $ctx"
            fi
        done
    fi
    echo ""
fi

# ---------------------------------------------------------------- Docs section
if [[ ${#docs_data[@]} -gt 0 ]]; then
    docs_lines=0
    for entry in "${docs_data[@]}"; do
        IFS='|' read -r lines filepath status added deleted <<< "$entry"
        docs_lines=$((docs_lines + lines))
    done

    echo "## Docs (${#docs_data[@]} files, $docs_lines lines)"
    echo ""
    for entry in "${docs_data[@]}"; do
        IFS='|' read -r lines filepath status added deleted <<< "$entry"
        echo "  $filepath	$lines$(annotate "$status" "$added" "$deleted")"
    done
    echo ""
fi

# ------------------------------------------------------------- Ignored section
if [[ ${#ignored_data[@]} -gt 0 ]]; then
    echo "## Ignored (${#ignored_data[@]} files)"
    echo ""
    for entry in "${ignored_data[@]}"; do
        IFS='|' read -r filepath reason <<< "$entry"
        echo "  $filepath	$reason"
    done
    echo ""
fi
